print("delete_all.py: Delete all files and folders including this script. Only the empty tools folder will remain. Us this as a last resort tool if CPanels GIT tool is pissed about file diffs.")
print("-"*100)
print("delete_db.py: Delete the nodeData db file. Us this if CPanels GIT tool is pissed about the file diffs")
print("-"*100)
print("clear_db.py: Clear the nodeData DBs contents")
print("-"*100)
print("write_wsgi.py: Write the correct contents into the passenger_wsgi.py file. If you recieve a 500 error, the CPanel Python interface probably overwrote it.")
print("-"*100)
print("show.py: Show the parent folder contents and its subfolders.")